[server]
headless = false
enableCORS = true
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#3b82f6"
backgroundColor="#0a1128"
secondaryBackgroundColor="#1e293b"
textColor="#e0e7ff"

